use anyhow::Result;
use clap::{Parser, Subcommand};

use crate::cli::VTClient;

fn require_auth(auth: &Option<String>) -> Result<String> {
    auth.clone()
        .ok_or_else(|| anyhow::anyhow!("VT_AUTH not set — run `vt-yubi init` and export the token"))
}

#[cfg(feature = "server")]
mod audit;
mod cli;
mod core;
mod security;
#[cfg(feature = "server")]
mod serve;
#[cfg(feature = "server")]
mod ssh_agent;
#[cfg(feature = "server")]
mod ssh_cli;
#[cfg(feature = "server")]
mod yk_backend;

#[derive(Parser)]
#[command(
    author,
    version,
    about = "a simple kms backed by YubiKey PIV. no plain, explicit auth everywhere"
)]
struct Cli {
    #[arg(
        long,
        global = true,
        env = "VT_ADDR",
        hide_env = true,
        help = "Host and port in the format host:port, e.g. 127.0.0.1:5757 (env: VT_ADDR)"
    )]
    addr: Option<String>,

    #[arg(
        long,
        global = true,
        env = "VT_AUTH",
        hide_env = true,
        help = "Authorization token, generated by `vt-yubi init` command (env: VT_AUTH)"
    )]
    auth: Option<String>,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, PartialEq)]
enum Commands {
    /// Show version information
    Version,
    /// Will read plain text and output encrypted message for you
    Create {
        #[arg(short = 'd', long = "description", help = "Description for the secret")]
        description: Option<String>,
        #[arg(
            short = 'f',
            long = "file",
            help = "Read secret value from a file (use - for stdin)"
        )]
        file: Option<String>,
    },
    /// List created secrets with descriptions and vt:// ciphertext
    List {
        #[arg(
            short = 's',
            long = "search",
            help = "Search secrets by description keyword"
        )]
        search: Option<String>,
    },
    /// Delete a secret from the local index by its number (shown in `vt list`)
    Delete {
        #[arg(help = "Secret number to delete (as shown in `vt list`)")]
        number: usize,
    },
    /// Decrypt an existing vt protocol as plaintext
    Read {
        #[arg(
            help = "A vt:// protocol string (e.g. vt://mac/0xxxx), or a number from `vt-yubi list` (e.g. 1)"
        )]
        vt: String,

        #[arg(short = 'c', long, help = "Copy TOTP code to clipboard (macOS only)")]
        copy: bool,
    },
    /// Read env/file and decrypt vt protocol, output to output-file or standard output
    Inject {
        #[arg(
            short = 'r',
            long = "replace-file",
            help = "Path to the file to replace with the decrypted vt protocol"
        )]
        replace_file: Option<String>,

        #[arg(short = 'i', long = "input-file", help = "Path to the input file")]
        input_file: Option<String>,

        #[arg(short = 'o', long = "output-file", help = "Path to the output file")]
        output_file: Option<String>,

        #[arg(
            short = 't',
            long,
            default_value = "2",
            help = "Timeout for deleting output_file after the spawned process in seconds"
        )]
        timeout: u32,

        #[arg(
            trailing_var_arg = true,
            help = "Additional arguments to pass to the spawned process"
        )]
        args: Vec<String>,
    },

    /// Trigger bio auth on the vt server (for use with PAM, sudo, etc.)
    Auth {
        #[arg(long, help = "Reason shown in the bio auth prompt")]
        reason: Option<String>,
    },

    /// (Server) Run vt-yubi server (SSH agent + optional HTTP). Requires YubiKey.
    #[cfg(feature = "server")]
    Serve {
        #[arg(
            long = "enable-http",
            default_value_t = false,
            help = "Enable the HTTP server for encrypt/decrypt endpoints"
        )]
        enable_http: bool,
        #[arg(
            long = "ssh-idle-timeout",
            default_value_t = ssh_agent::DEFAULT_IDLE_TIMEOUT_SECS,
            help = "SSH agent idle timeout in seconds before clearing keys from memory"
        )]
        ssh_idle_timeout: u64,
        #[arg(
            long = "ssh-auth-cache-mode",
            default_value = "none",
            help = "Auth cache mode: none, per-session, or per-app"
        )]
        auth_cache_mode: ssh_agent::AuthCacheMode,
        #[arg(
            long = "ssh-auth-cache-duration",
            default_value_t = ssh_agent::DEFAULT_AUTH_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds for sign operations"
        )]
        auth_cache_duration: u64,
        #[arg(
            long = "ssh-decrypt-cache-duration",
            default_value_t = ssh_agent::DEFAULT_DECRYPT_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds for decrypt operations"
        )]
        decrypt_cache_duration: u64,
    },
    /// (Server) Initialize YubiKey PIV key and encrypted secrets. Requires YubiKey.
    #[cfg(feature = "server")]
    Init {
        #[arg(
            long = "pubkey",
            help = "Path to an existing PIV public key (PEM or DER). Use this when the PIV private key was imported into slot 9d externally (e.g. for a shared key across multiple YubiKeys). When omitted, a new key is generated on the YubiKey."
        )]
        pubkey: Option<String>,
    },
    /// (Server) Manage master secret. Requires YubiKey.
    #[cfg(feature = "server")]
    #[command(subcommand)]
    Secret(SecretCommands),
    /// (Server) SSH agent and key management. Requires YubiKey.
    #[cfg(feature = "server")]
    #[command(subcommand)]
    Ssh(SshCommands),
}

#[cfg(feature = "server")]
#[derive(Subcommand, PartialEq)]
pub enum SecretCommands {
    /// Export the encrypted master secret
    Export,
    /// Import an encrypted master secret
    Import,
}

#[cfg(feature = "server")]
#[derive(Subcommand, PartialEq)]
pub enum SshCommands {
    /// Start the SSH agent (listens on ~/.ssh/vt-yubi.sock)
    Agent {
        #[arg(
            short = 't',
            long = "timeout",
            default_value_t = ssh_agent::DEFAULT_IDLE_TIMEOUT_SECS,
            help = "Idle timeout in seconds before clearing keys from memory"
        )]
        timeout: u64,
        #[arg(
            long = "ssh-auth-cache-mode",
            default_value = "none",
            help = "Auth cache mode: none, per-session, or per-app"
        )]
        auth_cache_mode: ssh_agent::AuthCacheMode,
        #[arg(
            long = "ssh-auth-cache-duration",
            default_value_t = ssh_agent::DEFAULT_AUTH_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds for sign operations"
        )]
        auth_cache_duration: u64,
        #[arg(
            long = "ssh-decrypt-cache-duration",
            default_value_t = ssh_agent::DEFAULT_DECRYPT_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds for decrypt operations"
        )]
        decrypt_cache_duration: u64,
    },
    /// Add an SSH private key (ECDSA P-256/P-384 only)
    Add {
        #[arg(short = 'f', long = "file", help = "Path to the SSH private key file")]
        file: Option<String>,
        #[arg(
            short = 'c',
            long = "comment",
            help = "Comment for the key (overrides key's embedded comment)"
        )]
        comment: Option<String>,
    },
    /// List stored SSH keys
    List,
    /// Remove an SSH key by fingerprint
    Remove {
        #[arg(help = "Fingerprint (or prefix) of the key to remove")]
        fingerprint: String,
    },
    /// Remove all stored SSH keys
    RemoveAll,
    /// Change the comment of a stored SSH key
    Comment {
        #[arg(help = "Fingerprint (or prefix) of the key to update")]
        fingerprint: String,
        #[arg(short = 'c', long = "comment", help = "New comment for the key")]
        comment: String,
    },
    /// Show the public key for a stored SSH key
    Show {
        #[arg(help = "Fingerprint (or prefix) of the key to show")]
        fingerprint: String,
    },
}

async fn run(cli: Cli) -> Result<()> {
    match &cli.command {
        Commands::Version => {
            println!("vt-yubi {}", env!("CARGO_PKG_VERSION"));
            return Ok(());
        }

        // --- Server commands (require YubiKey + "server" feature) ---
        #[cfg(feature = "server")]
        Commands::Serve {
            enable_http,
            ssh_idle_timeout,
            auth_cache_mode,
            auth_cache_duration,
            decrypt_cache_duration,
        } => {
            serve::serve(
                cli.addr.as_deref().unwrap_or("127.0.0.1:5757"),
                *enable_http,
                *ssh_idle_timeout,
                *auth_cache_mode,
                *auth_cache_duration,
                *decrypt_cache_duration,
            )
            .await
        }
        #[cfg(feature = "server")]
        Commands::Init { pubkey } => cli::init(pubkey.clone()),
        #[cfg(feature = "server")]
        Commands::Secret(secret_command) => match secret_command {
            SecretCommands::Export => cli::export_secret().await,
            SecretCommands::Import => cli::import_secret().await,
        },
        #[cfg(feature = "server")]
        Commands::Ssh(ssh_command) => match ssh_command {
            SshCommands::Agent {
                timeout,
                auth_cache_mode,
                auth_cache_duration,
                decrypt_cache_duration,
            } => {
                ssh_agent::start_ssh_agent(
                    *timeout,
                    *auth_cache_mode,
                    *auth_cache_duration,
                    *decrypt_cache_duration,
                )
                .await
            }
            SshCommands::Add { file, comment } => ssh_cli::ssh_add(file.clone(), comment.clone()),
            SshCommands::List => ssh_cli::ssh_list(),
            SshCommands::Remove { fingerprint } => ssh_cli::ssh_remove(fingerprint),
            SshCommands::RemoveAll => ssh_cli::ssh_remove_all(),
            SshCommands::Comment {
                fingerprint,
                comment,
            } => ssh_cli::ssh_comment(fingerprint, comment),
            SshCommands::Show { fingerprint } => ssh_cli::ssh_show(fingerprint),
        },

        // --- Client commands (no YubiKey needed) ---
        Commands::Create { description, file } => {
            let auth = require_auth(&cli.auth)?;
            let vt_client = VTClient::new(cli.addr.clone(), auth);
            cli::create(vt_client, description.clone(), file.clone()).await
        }
        Commands::List { search } => cli::list(search.clone()),
        Commands::Delete { number } => cli::delete(*number),
        Commands::Read { vt, copy } => {
            let auth = require_auth(&cli.auth)?;
            let vt_client = VTClient::new(cli.addr.clone(), auth);
            cli::read(vt_client, vt.to_string(), *copy).await
        }
        Commands::Auth { reason } => {
            let auth = require_auth(&cli.auth)?;
            let vt_client = VTClient::new(cli.addr.clone(), auth);
            cli::auth(vt_client, reason.as_deref().unwrap_or("bio auth requested")).await
        }
        Commands::Inject {
            replace_file,
            input_file,
            output_file,
            timeout,
            args,
        } => {
            let auth = require_auth(&cli.auth)?;
            let vt_client = VTClient::new(cli.addr.clone(), auth);
            cli::inject(
                vt_client,
                replace_file.clone(),
                input_file.clone(),
                output_file.clone(),
                *timeout,
                args.clone(),
            )
            .await
        }
    }
}

#[tokio::main]
async fn main() {
    let log_level = std::env::var("RUST_LOG")
        .unwrap_or_else(|_| {
            if cfg!(debug_assertions) {
                "debug".to_string()
            } else {
                "info".to_string()
            }
        })
        .parse::<tracing::Level>()
        .unwrap_or(tracing::Level::INFO);
    tracing_subscriber::fmt()
        .with_max_level(log_level)
        .with_target(true)
        .with_line_number(true)
        .compact()
        .init();
    let cli = Cli::parse();

    if let Err(e) = run(cli).await {
        tracing::error!("Command failed: {:?}", e);
        std::process::exit(1);
    }
}
