use clap::{Parser, Subcommand};

use crate::cli::VTClient;

mod cli;
mod core;
mod security;
mod serve;
#[cfg(target_os = "macos")]
mod ssh_agent;
#[cfg(target_os = "macos")]
mod ssh_cli;

#[derive(Parser)]
#[command(author, version, about="a simple kms. no plain, explicit auth everywhere")]
struct Cli {
    #[arg(
        long,
        global = true,
        env = "VT_ADDR",
        help = "Host and port in the format host:port, e.g. 127.0.0.1:5757"
    )]
    addr: Option<String>,

    #[arg(
        long,
        global = true,
        env = "VT_AUTH",
        default_value = "MY5hkACZQZbqfpuYaWjnzlbpGVQYhwqynnrpkek568g",
        help = "Authorization header value, generated by `vault init` command"
    )]
    auth: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, PartialEq)]
enum Commands {
    /// Will read plain text and output encrypted message for you
    Create,
    /// Decrypt an existing vt protocol as plaintext
    Read {
        #[arg(help = "A string in vt protocol format, e.g. vt://mac/0xxxx")]
        vt: String,
    },
    /// Read env/file and decrypt vt protocol, output to output-file or standard output
    Inject {
        #[arg(
            short = 'r',
            long = "replace-file",
            help = "Path to the file to replace with the decrypted vt protocol"
        )]
        replace_file: Option<String>,

        #[arg(short = 'i', long = "input-file", help = "Path to the input file")]
        input_file: Option<String>,

        #[arg(short = 'o', long = "output-file", help = "Path to the output file")]
        output_file: Option<String>,

        #[arg(
            short = 't',
            long,
            default_value = "2",
            help = "Timeout for deleting output_file after the spawned process in seconds"
        )]
        timeout: u32,

        #[arg(
            trailing_var_arg = true,
            help = "Additional arguments to pass to the spawned process"
        )]
        args: Vec<String>,
    },

    #[cfg(target_os = "macos")]
    /// (Mac only) Run vt server
    Serve {
        #[arg(
            long = "ssh-idle-timeout",
            default_value_t = ssh_agent::DEFAULT_IDLE_TIMEOUT_SECS,
            help = "SSH agent idle timeout in seconds before clearing keys from memory (default: 1800 = 30min)"
        )]
        ssh_idle_timeout: u64,
        #[arg(
            long = "ssh-auth-cache-mode",
            default_value = "none",
            help = "Auth cache mode: none, per-session, or per-app"
        )]
        auth_cache_mode: ssh_agent::AuthCacheMode,
        #[arg(
            long = "ssh-auth-cache-duration",
            default_value_t = ssh_agent::DEFAULT_AUTH_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds (default: 300 = 5min)"
        )]
        auth_cache_duration: u64,
    },
    /// (Mac only) Initialize passcode, passphrase which will be used by server
    #[cfg(target_os = "macos")]
    Init,
    /// (Mac only) Manage master secret
    #[cfg(target_os = "macos")]
    #[command(subcommand)]
    Secret(SecretCommands),
    /// (Mac only) SSH agent and key management
    #[cfg(target_os = "macos")]
    #[command(subcommand)]
    Ssh(SshCommands),
}

#[cfg(target_os = "macos")]
#[derive(Subcommand, PartialEq)]
pub enum SecretCommands {
    /// Export the encrypted master secret
    Export,
    /// Import an encrypted master secret
    Import,
    /// Rotate the passcode for the master secret
    RotatePasscode {
        #[arg(long, help = "Absolute path to the new vt binary")]
        bin_absolute_path: Option<String>,
    },
}

#[cfg(target_os = "macos")]
#[derive(Subcommand, PartialEq)]
pub enum SshCommands {
    /// Start the SSH agent (listens on ~/.ssh/vt.sock)
    Agent {
        #[arg(
            short = 't',
            long = "timeout",
            default_value_t = ssh_agent::DEFAULT_IDLE_TIMEOUT_SECS,
            help = "Idle timeout in seconds before clearing keys from memory (default: 1800 = 30min)"
        )]
        timeout: u64,
        #[arg(
            long = "ssh-auth-cache-mode",
            default_value = "none",
            help = "Auth cache mode: none, per-session, or per-app"
        )]
        auth_cache_mode: ssh_agent::AuthCacheMode,
        #[arg(
            long = "ssh-auth-cache-duration",
            default_value_t = ssh_agent::DEFAULT_AUTH_CACHE_DURATION_SECS,
            help = "Auth cache duration in seconds (default: 300 = 5min)"
        )]
        auth_cache_duration: u64,
    },
    /// Add an SSH private key to the keychain
    Add {
        #[arg(short = 'f', long = "file", help = "Path to the SSH private key file")]
        file: Option<String>,
        #[arg(short = 'c', long = "comment", help = "Comment for the key (overrides key's embedded comment)")]
        comment: Option<String>,
    },
    /// List stored SSH keys
    List,
    /// Remove an SSH key by fingerprint
    Remove {
        #[arg(help = "Fingerprint (or prefix) of the key to remove")]
        fingerprint: String,
    },
    /// Remove all stored SSH keys
    RemoveAll,
    /// Change the comment of a stored SSH key
    Comment {
        #[arg(help = "Fingerprint (or prefix) of the key to update")]
        fingerprint: String,
        #[arg(short = 'c', long = "comment", help = "New comment for the key")]
        comment: String,
    },
    /// Show the public key for a stored SSH key
    Show {
        #[arg(help = "Fingerprint (or prefix) of the key to show")]
        fingerprint: String,
    },
}

#[tokio::main]
async fn main() {
    let log_level = std::env::var("RUST_LOG")
        .unwrap_or_else(|_| {
            if cfg!(debug_assertions) {
                "debug".to_string()
            } else {
                "info".to_string()
            }
        })
        .parse::<tracing::Level>()
        .unwrap_or(tracing::Level::INFO);
    tracing_subscriber::fmt()
        .with_max_level(log_level)
        .with_target(true)
        .with_line_number(true)
        .compact()
        .init();
    let cli = Cli::parse();

    let command_result = match &cli.command {
        #[cfg(target_os = "macos")]
        Commands::Serve { .. } | Commands::Init => match &cli.command {
            Commands::Serve {
                ssh_idle_timeout,
                auth_cache_mode,
                auth_cache_duration,
            } => {
                serve::serve(
                    cli.addr.as_deref().unwrap_or("127.0.0.1:5757"),
                    *ssh_idle_timeout,
                    *auth_cache_mode,
                    *auth_cache_duration,
                )
                .await
            }
            Commands::Init => cli::init(),
            _ => unreachable!(),
        },
        #[cfg(target_os = "macos")]
        Commands::Secret(secret_command) => match secret_command {
            SecretCommands::Export => cli::export_secret().await,
            SecretCommands::Import => cli::import_secret().await,
            SecretCommands::RotatePasscode { bin_absolute_path } => {
                cli::rotate_passcode(bin_absolute_path.clone()).await
            }
        },
        #[cfg(target_os = "macos")]
        Commands::Ssh(ssh_command) => match ssh_command {
            SshCommands::Agent {
                timeout,
                auth_cache_mode,
                auth_cache_duration,
            } => ssh_agent::start_ssh_agent(*timeout, *auth_cache_mode, *auth_cache_duration).await,
            SshCommands::Add { file, comment } => ssh_cli::ssh_add(file.clone(), comment.clone()),
            SshCommands::List => ssh_cli::ssh_list(),
            SshCommands::Remove { fingerprint } => ssh_cli::ssh_remove(fingerprint),
            SshCommands::RemoveAll => ssh_cli::ssh_remove_all(),
            SshCommands::Comment { fingerprint, comment } => ssh_cli::ssh_comment(fingerprint, comment),
            SshCommands::Show { fingerprint } => ssh_cli::ssh_show(fingerprint),
        },
        Commands::Create => {
            let vt_client = VTClient::new(cli.addr.clone(), cli.auth.clone());
            cli::create(vt_client).await
        }
        Commands::Read { vt } => {
            let vt_client = VTClient::new(cli.addr.clone(), cli.auth.clone());
            cli::read(vt_client, vt.to_string()).await
        }
        Commands::Inject {
            replace_file,
            input_file,
            output_file,
            timeout,
            args,
        } => {
            let vt_client = VTClient::new(cli.addr.clone(), cli.auth.clone());
            cli::inject(
                vt_client,
                replace_file.clone(),
                input_file.clone(),
                output_file.clone(),
                *timeout,
                args.clone(),
            )
            .await
        }
    };
    if command_result.is_err() {
        tracing::error!("Command failed: {:?}", command_result);
        std::process::exit(1);
    }
}
